apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-market-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-market-api
  template:
    metadata:
      labels:
        app: stock-market-api
    spec:
      containers:
      - name: stock-market-api
        image: stockmarketappregistry.azurecr.io/stock-market-app-api:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/dev
      imagePullSecrets:
        - name: mydockerregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: stock-market-api
spec:
  type: LoadBalancer
  ports:
  - port: 9091
  selector:
    app: stock-market-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-market-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-market-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: stock-market-front
    spec:
      containers:
      - name: stock-market-front
        image: stockmarketappregistry.azurecr.io/stock-market-app-front:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: mydockerregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: stock-market-front
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: stock-market-front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017