apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-database
  name: api-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/back-tier: "true"
        io.kompose.service: api-database
    spec:
      containers:
        - image: mongo:latest
          name: api-database
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: api-database-claim0
      restartPolicy: Always
      volumes:
        - name: api-database-claim0
          persistentVolumeClaim:
            claimName: api-database-claim0
status: {}
