apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-manager
  name: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-manager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/elk: "true"
        io.kompose.service: kafka-manager
    spec:
      containers:
        - env:
            - name: ZK_HOSTS
              value: kafkaserver:2181
          image: mzagar/kafka-manager-docker:1.3.3.4
          name: kafkamanager
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
