apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/elk: "true"
        io.kompose.service: kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
          image: kibana:7.0.1
          name: kibana
          ports:
            - containerPort: 5601
          resources: {}
          volumeMounts:
            - mountPath: /opt/kibana/config/
              name: kibana-claim0
      restartPolicy: Always
      volumes:
        - name: kibana-claim0
          persistentVolumeClaim:
            claimName: kibana-claim0
status: {}
