apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/elk: "true"
        io.kompose.service: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.0.1
          
          env:
            - name: XPACK_MONITORING_ENABLED
              value: "false"
            - name: XPACK_REPORTING_ENABLED
              value: "false"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
          ports:
            - containerPort: 9999
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/config:rw
              name: logstash-settings-config-volume
            - mountPath: /usr/share/logstash/pipeline:rw
              name: logstash-pipeline-config-volume  
      restartPolicy: Always
      volumes:
        - name: logstash-settings-config-volume
          configMap:
            name: logstash-config
            items:
              - key: "logstash.yml"
                path: logstash.yml
        - name: logstash-pipeline-config-volume
          configMap:
            name: logstash-config
            items:
              - key: "pipeline.conf"
                path: pipeline.conf       
status: {}
